version: '3'

services:
    db:
      container_name: postgres
      image: postgres
      env_file:
        - ./postgres/.env
      ports:
        - "5432:5432"
      volumes:
        - pg_data:/var/lib/postgresql/data
    web:
      container_name: django
      build: .
      command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
      volumes:
        - .:/code
      expose:
        - "8000"
      env_file:
        - ./.env
      depends_on:
        - db
    nginx:
      container_name: nginx
      build: ./nginx
      volumes:
        - ./static:/usr/src/app/static
        - ./media:/usr/src/app/media
      ports:
        - "80:80"
      depends_on:
        - web

volumes:
  pg_data:
